#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

BAR_DIR="$HOME/.config/sketchybar/bar"
ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored



FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
# HELPER=git.felix.helper
# killall helper
# cd $HOME/.config/sketchybar/helper && make
# $HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
#launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &



# Setting up default values
defaults=(
  updates=when_shown
  icon.font="sketchybar-app-font:Regular:20.0"
  icon.color=0xff539bf5
  label.font="Maple Mono NF CN:Semibold:16.0"
  label.color=0xff1c1c1e
  padding_right=0
  padding_left=0
  background.height=26
  background.corner_radius=5
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  
)
sketchybar --default "${defaults[@]}"


source "$BAR_DIR/bottombar.sh"

# Left
#source "$ITEM_DIR/apple.sh"
#source "$ITEM_DIR/spaces.sh"
#source "$ITEM_DIR/yabai_float.sh"
#source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/media.sh"
# Right
#source "$ITEM_DIR/calendar.sh"
# #source "$ITEM_DIR/mail.sh"
#source "$ITEM_DIR/messenger.sh"
##source "$ITEM_DIR/mattermost.sh"
#source "$ITEM_DIR/wechat.sh"
#source "$ITEM_DIR/battery.sh"
#source "$ITEM_DIR/airpods_status.sh"
#source "$ITEM_DIR/volume.sh"



# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
