#!/bin/sh

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source $CONFIG_DIR/colors.sh
source $CONFIG_DIR/icons.sh
source $CONFIG_DIR/settings.sh

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

bar=( 
    color=0x8820263a
    border_color=0x44999999
    border_width=1
    position=top
    height=38
    margin=-1
    padding_left=18 
    padding_right=10 
    notch_display_height=0
    notch_width=200
    notch_offset=0
    y_offset=-1
    corner_radius=12
    blur_radius=36
    shadow=on
    sticky=on
    topmost=off
    display=all
    hidden=off
    font_smoothing=off
)
sketchybar --bar "${bar[@]}"


sketchybar --default \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    background.color=0x9924273a \
    icon.font="$FONT_ICON:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_LABEL:Medium:12.0" \
    label.color=0xffffffff \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5 \
    popup.background.color=0xee1c1c1e \
	popup.background.border_color=0xffcccccc \
	popup.background.border_width=1 \
	popup.background.corner_radius=16 \
	popup.height=34

# 
# LEFT
# 
source "$ITEMS_DIR/apple.sh"

source "$ITEMS_DIR/aerospace.sh"

source "$ITEMS_DIR/front_app.sh"

source "$ITEMS_DIR/cpu.sh"

source "$ITEMS_DIR/status.sh"

# 
# CENTER
# 
#source "$ITEMS_DIR/weather.sh"
sketchybar -m --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon=􁒙\
    icon.y_offset=1 \
    icon.font="$FONT_ICON:Bold:16.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

source "$ITEMS_DIR/message.sh"




# 
# RIGHT
# 
#source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/calendar.sh"

source "$ITEMS_DIR/volume.sh"

source "$ITEMS_DIR/airpods.sh"

source "$ITEMS_DIR/battery.sh"

source "$ITEMS_DIR/network.sh"

# source "$ITEMS_DIR/net.sh"


##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
