#!/usr/bin/env sh

options=(
  # Sets the border color for the focused window (format: 0xff38bdf8). 
  active_color=gradient(top_left=0xff38bdf8,bottom_right=0xff98ff98)
  # Sets the border color for all windows not in focus (format: 0xffbfdbfe). 
  inactive_color=gradient(top_left=0xffbfdbfe,bottom_right=0xffc4b5fd)
  order=above         # Specifies whether borders should be drawn above or below windows.
  style=round         # Specifies the style of the border (either round or square).
  blur_radius=20.0  # blur radius applied to the borders or backgrounds with transparency.
  width=3.0         # Determines the width of the border
  hidpi=on        # If set to on, the border will be drawn with retina resolution.
  ax_focus=off
  blacklist="kitty"
)

borders "${options[@]}"